#!/bin/sh

ROUTE=$(route -n | grep 'UG[ \t ]' | awk '{print $2}')
CONSUL=${ROUTE}:8500

nc -z $ROUTE 8500
rc=$?

if [ $rc != 0 ]; then
  echo "WARNING! Consul not available, running locally."
  $2
else
  /usr/bin/envconsul -consul=${CONSUL} -config /etc/envconsul-config.hcl $*
fi
