#!/bin/sh

if [ -z "$CONSUL" ]; then
  ROUTE=$(route -n | grep 'UG[ \t ]' | awk '{print $2}')
  CONSUL=${ROUTE}
fi

nc -z $CONSUL 8500
rc=$?

if [ $rc != 0 ]; then
  echo "WARNING! Consul not available, running locally."
  $2
else
  /usr/bin/envconsul -consul=${CONSUL}:8500 -config /etc/envconsul-config.hcl $*
fi
